name: pipeline ci

on:
  #for testing purpose
  push:
  #Make your workflow trigger on pull request.
  pull_request:
    #Make your workflow trigger on pull request and only when specific files are changed
    paths:
      - "app/*.py"
  workflow_dispatch:

jobs:
  setup_python:
    name: set up python 3.10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      # Run a simple workflow with: * lint
      - name: Run Pylint
        run: |
          pylint --disable=all --enable=unused-import $(git ls-files 'app/*.py')

      - name: Editorconfig check
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        with:
          black_args: "./app"
          fail_on_error: true